name = "nextlist"
main = "src/backend/worker.ts"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[assets]
directory = "./dist"
binding = "ASSETS"


[vars]
ENVIRONMENT = "production"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
VITE_API_URL = "/api"

[[kv_namespaces]]
binding = "NEXTLIST_KV"
id = "ce0c9fd9ad104509bb0630c333da68ab"




